<?php

$languages = array('English','Korean','Hindi','Japanese','Chinese','Tamil','Arabic','Spanish','Marathi','English/Hindi','English/Korean','German','Kannada','Malayalam','English/Thai','Taiwanese','Ukrainian');

$venues = array('Netflix','Viki','MasterClass','YouTube','ErosNow','Amazon Video','iTunes','In-flight entertainment','Movie theater','EconLib','HBO');

$years = array('2022', '2021','2020','2019','2018','2017','2016','2015','2014','2013','2012');

?>
