create table ongoing_consumption(
  ongoing_consumption_id int(11) not null auto_increment primary key,
  format enum('Series (such as TV show or web series)','Single video (such as movie)','YouTube channel','Podcast'),
  primary_language enum('English','Korean','Hindi','Japanese','Chinese','Tamil','Arabic','Spanish','Marathi','English/Hindi','English/Korean','German','Kannada','Malayalam','English/Thai','Taiwanese','Ukrainian'),
  item varchar(200),
  url varchar(200),
  notes varchar(2000)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

insert into ongoing_consumption(format, primary_language, item, url, notes) values
  ('Series (such as TV show or web series)','English','Gilmore Girls','https://www.amazon.com/gp/video/detail/B002DEI4NG/','Starting around 2020 or 2021, I''ve been rewatching Gilmore Girls (seasons 1 through 7, as well as A Year in the life) off and on. I have done both systematic start-to-end rewatches and random watching of specific episodes that I like. I find Gilmore Girls relaxing to watch. I usually don''t watch it during meals, but often watch it when doing somewhat boring and not-fully-engaging work, to provide a little additional stimulation without being distracting (because I know the storyline very well). I own all seasons but not A Year in the Life. So I can watch anything from seasons 1 through 7 whenever I wish, but for A Year in the Life I can only watch it when I''m subscribed to Netflix.'),
  ('Single video (such as movie)','Hindi','Dilwale Dulhania Le Jayenge',NULL,'I bought the VCD for this in 2006 and copied it to disk around 2007, 2008, or 2009 back when I was using a Windows machine. I have watched parts of this classic movie off and on. I didn''t watch it between 2014 and 2019 after I switched to a Macbook. I loaded it up again on my Macbook at the end of 2019 and then watched it a bit in 2020. In 2022, after getting a new, bigger Macbook, I resumed watching it. It''s very familiar to me. I usually don''t watch it during meals, but often watch it when doing somewhat boring and not-fully-engaging work, to provide a little additional stimulation without being distracting (because I know the storyline very well).'),
  ('Single video (such as movie)','Hindi','Jab We Met',NULL,'My parents gifted me the VCD for this in the late 2000s or early 2010s. I loaded it on my Windows machine and would watch parts of it. I didn''t watch it between 2014 and 2019 after I switched to a Macbook. I loaded it up again on my Macbook at the end of 2019 and then watched it a bit in 2020. In 2022, after getting a new, bigger Macbook, I resumed watching it. It''s very familiar to me. I usually don''t watch it during meals, but often watch it when doing somewhat boring and not-fully-engaging work, to provide a little additional stimulation without being distracting (because I know the storyline very well).'),
  ('Single video (such as movie)','Hindi','Anjaana Anjaani',NULL,'I bought the VCD for this during a trip to India in 2011. I loaded it on my Windows machine and would watch parts of it. I didn''t watch it between 2014 and 2019 after I switched to a Macbook. I loaded it up again on my Macbook at the end of 2019 and then watched it a bit in 2020. In 2022, after getting a new, bigger Macbook, I resumed watching it. It''s very familiar to me. I usually don''t watch it during meals, but often watch it when doing somewhat boring and not-fully-engaging work, to provide a little additional stimulation without being distracting (because I know the storyline very well).'),
  ('Single video (such as movie)','Hindi','My Name Is Khan',NULL,'My parents may have gifted the VCD to me in the early 2010s or I may have bought it -- I''m not sure.  I didn''t watch it between 2014 and 2019 after I switched to a Macbook. I loaded it up again on my Macbook at the end of 2019 and then watched it a bit in 2020. In 2022, after getting a new, bigger Macbook, I resumed watching it. It''s very familiar to me. I usually don''t watch it during meals, but often watch it when doing somewhat boring and not-fully-engaging work, to provide a little additional stimulation without being distracting (because I know the storyline very well).'),
  ('YouTube channel','English','Veritasium','https://www.youtube.com/c/veritasium','I often watch Veritasium videos while doing not-fully-engaging work. Veritasium provides good intellectual stimulation and I also learn some useful stuff from it. I originally started watching Veritasium in the early 2010s, but then didn''t watch it for several years. I resumed watching Veritasium videos in 2022. I don''t record each individual video viewed, since I watch so many and they are not individually that noteworthy.'),
  ('YouTube channel','English','Ali Abdaal','https://www.youtube.com/channel/UCoOae5nYA7VqaXzerajD0lg','I''ve watched several videos of Ali Abdaal ever since hearing about him in December 2021. I do record individual videos of his that I watch if they were significant for me and/or if they were long. However, I have watched several short videos by him that I don''t feel are worth recording individually.'),
  ('YouTube channel','English','Magnates Media','https://www.youtube.com/c/MagnatesMedia','Starting August 2022, I''ve watched several Magnates Media videos that cover timelines of tech companies and other things in the tech world. I like the format of these. Another motivation for watching them is to get inspiration for how to make timelines on Timelines Wiki better. It doesn''t seem worthwhile to record which specific videos I watched.'),
  ('Podcast','English','Making Sense Podcast (with Sam Harris)','https://www.samharris.org/podcasts','Starting September 2022, I listened to the free (usually truncated) versions of many episodes of the Making Sense podcast by Sam Harris. For the most part, I have not been recording the consumption of individual episodes.'),
  ('YouTube channel','English/Hindi','ThePrint','https://www.youtube.com/c/ThePrintIndia','Starting around September 2021, I''ve watched several YouTube videos from ThePrint. Most of them are in English by Shekhar Gupta and are part of his Cut The Clutter or National Interest series. I''ve also watched videos by others, some of them in Hindi.'),
  ('Podcast','English','I Am All In with Scott Patterson','https://omny.fm/shows/i-am-all-in-with-scott-patterson','I listened to a few episodes through 2022, but started listening to the podcast systematically (listening to their recaps of individual Gilmore Girls episodes) starting 2022-11-06.');
